# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusprocess',
            old_name='userProfile',
            new_name='user_profile',
        ),
    ]
